In [3]:
import turicreate
import numpy as np
import math

In [4]:
sales = turicreate.SFrame('~/Desktop/2.self_learning/coursera_washington/module2_regression/data/home_data.sframe')

In [6]:
def get_numpy_data(data, feature, output):
    
    data['constant'] = 1
    chosen_feature = ['constant'] + feature
    
    feature_array = data[chosen_feature].to_numpy()
    output_array  = data[output].to_numpy()
    
    return(feature_array,output_array)

In [45]:
def predicted_output(input_feature, given_weight):
    
    feature = np.array(input_feature)
    weight = np.array(given_weight)
    
    predicted_value = np.dot(feature,weight)
    
    return(predicted_value)

In [61]:
#derivative = 2 * errors * feature[i]
#error = predicted_output - output(true value)
def feature_derivative(errors, feature):
    
    ab = np.dot(errors, feature)
    derivative = 2 * ab
    
    return(derivative)

In [ ]:
def regression_gradient_descent(input_feature, output, initial_weights, step_size, tolerance):
    converged = False 
    weights = np.array(initial_weights) # make sure it's a numpy array
    while not converged:
        

## example practice

In [44]:
(ex_feature, ex_output) = get_numpy_data(sales,['sqft_living'],'price')

print(ex_feature) 
#[[constant of data_1,sqft_living of data_1 ],[constant of data_2, sqft_living of data_2],...total 21613]

print('output')
print(ex_output)
#[[price of data_1],[price of data_2],[price of data_3],..... total 21613]

[[1.00e+00 1.18e+03]
 [1.00e+00 2.57e+03]
 [1.00e+00 7.70e+02]
 ...
 [1.00e+00 1.02e+03]
 [1.00e+00 1.60e+03]
 [1.00e+00 1.02e+03]]
output
[221900. 538000. 180000. ... 402101. 400000. 325000.]


In [46]:
my_weight = np.array([1,1])

print(predicted_output(ex_feature,my_weight)) #value of feature multiple weight for 21613 data

[1181. 2571.  771. ... 1021. 1601. 1021.]


In [67]:
prediction = predicted_output(ex_feature, my_weight)
error = prediction - ex_output
print(prediction.shape)
print(ex_output.shape)
print(error.shape)
print(ex_feature.shape)

(21613,)
(21613,)
(21613,)
(21613, 2)


In [81]:
ans = feature_derivative(error, ex_feature[:,0]) #ex_feature[:,0] = [1,1,1,1,1,1]
print(ans)

# actually is the 2 * (total of errors (21613 data))
ans2 = sum(error)*2
print(ans2)

-23255901050.0
-23255901050.0


In [1]:
import numpy as np

In [6]:
x=np.array([[1,2,3],[3,4,5]])

In [9]:
x.T.shape

(3, 2)

In [11]:
x.shape

(2, 3)